project:
  type: website
  output-dir: docs

resources:
  - .nojekyll

website:
  title: "Tabaré Capitán"
  description: "Data scientist, personal website"
  favicon: favicon.png
  open-graph: true
  back-to-top-navigation: true
  reader-mode: false
  navbar:
    search: true

    left:
      - href: index.qmd
        text: about
      - href: projects/index.qmd
        text: projects
      - href: toolbox.qmd
        text: toolbox
      - href: research.qmd
        text: research
  sidebar:
    - id: "proj-ritest"
      title: "ritest"
      style: docked
      collapse-level: 2
      contents:
        - projects/ritest/index.qmd
        - projects/ritest/quick-start.qmd

        - section: "Examples"
          contents:
            - projects/ritest/examples/settings.qmd
            - projects/ritest/examples/non-linear.qmd
            - projects/ritest/examples/custom.qmd
            - projects/ritest/examples/did.qmd
            - projects/ritest/examples/multi-arm.qmd

        - section: "Benchmarks"
          contents:
            - projects/ritest/benchmarks/intro.qmd
            - projects/ritest/benchmarks/colombia.qmd
            - projects/ritest/benchmarks/generic-vs-linear.qmd
            - projects/ritest/benchmarks/ci-band.qmd

        - section: "Technical notes"
          contents:
            - projects/ritest/technical-notes/ri.qmd
            - projects/ritest/technical-notes/pvalues.qmd
            - projects/ritest/technical-notes/ci.qmd
            - projects/ritest/technical-notes/big-o.qmd

        - projects/ritest/api.qmd
      tools:
        - icon: github
          menu:
            - text: Source Code
              href:  https://github.com/tabareCapitan/ritest
            - text: Report a Bug
              href:  https://github.com/tabareCapitan/ritest/issues

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right
